trigger:
- master

pool:
  vmImage: windows-2019

variables:
  solution: '**/*.sqlproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sqlProjectPath: 'core/data_platform' # Adjust this path
  databaseName: 'dev01xctrldb'
  serverName: 'dev01xctrlserver.database.windows.net'
  resourceGroupName: 'dev-az-rg'
  sqlPackagePath: '$(Build.ArtifactStagingDirectory)/data_platform.dacpac'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build SQL Project'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(sqlProjectPath)/*.sqlproj'

    - task: VSBuild@1
      inputs:
        solution: '$(sqlProjectPath)/*.sqlproj'
        msbuildArgs: '/p:Configuration=Release'
        platform: 'Any CPU'
        configuration: 'Release'

    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'    

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azelia-dev-connection'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $dacpacFilePath = "$(sqlPackagePath)"
                $managedIdentityClientId = "d3e8813a-a336-4fde-ab4c-67afa86c639e"
                $resourceGroupName = "$(resourceGroupName)"
                $sqlServerName = "$(serverName)"
                $databaseName = "$(databaseName)"
     
                # Generate access token for Managed Identity
                $accessToken = az account get-access-token --resource https://database.windows.net/ --query accessToken --output tsv
                
                # Deploy DACPAC to Azure SQL Database
                & C:\Program Files\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe /Action:Publish /SourceFile:$dacpacFilePath /TargetServerName:$sqlServerName /TargetDatabaseName:$databaseName /AccessToken:$accessToken /p:AllowIncompatiblePlatform=true