
# Main

trigger:
- none
pool:
  vmImage: "ubuntu-latest"

stages:
#  - stage: BUILD
#    jobs:
#    - job: BuildAzureArtifacts
#      steps:
#      - publish: ''
#        displayName: 'Publish Artifact: azure_resources'
#        artifact: azure_resources

  - stage: DEV
    jobs:
    - job: DeployAzureArtifacts
      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Subscription'
          azureResourceManagerConnection: 'azelia-dev-connection'
          templateLocation: 'Linked artifact'
          location: 'uksouth'
          csmFile: 'core/bicep/platform.bicep'
          csmParametersFile: 'core/bicep/infrastructure.bicepparam'
          deploymentMode: Incremental
          deploymentName: 'InfrastructureDeployment'

#      - task: PowerShell@2
#        inputs:
#          filePath: 'platform/scripts/deploy.ps1'
#          arguments: '-armTemplateOutput ''$(deploymentOutputs)'''


#stages:
#  # SQL Stages
#  - stage: Preview_SQL
#    jobs:
#    - job: Preview
#      steps:
#      - task: AzureCLI@2
#        inputs:
#          azureSubscription: $(serviceConnection)
#          scriptType: 'bash'
#          scriptLocation: 'inlineScript'
#          inlineScript: |
#            az deployment group create \
#              --resource-group $(resourceGroupName) \
#              --name "SQL-deployment" \
#              --template-file Bicep/SQL/SQL-tst.bicep \
#              --parameters Environment="${{ parameters.Environment}}" sqladminlogin=Some_value sqladminpassword=Some_value