trigger:
- master

pool:
  vmImage: windows-2019

variables:
  solution: '**/*.sqlproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sqlProjectPath: 'path/to/your/sql/project' # Adjust this path
  databaseName: 'dev01xctrldb'
  serverName: 'dev01xctrlserver.database.windows.net'
  resourceGroupName: 'dev-az-rg'
  sqlPackagePath: '$(Build.ArtifactStagingDirectory)/YourDatabase.dacpac'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build SQL Project'
    steps:
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    # Add those tasks to copy and publish the Artifact (.dacpac file)
    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'    

    - task: PublishBuildArtifacts@1    
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azelia-dev-connection'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $dacpacFilePath = "$(sqlPackagePath)"
                $managedIdentityClientId = "d3e8813a-a336-4fde-ab4c-67afa86c639e"
                $resourceGroupName = "$(resourceGroupName)"
                $sqlServerName = "$(serverName)"
                $databaseName = "$(databaseName)"
                
                # Generate access token for Managed Identity
                $accessToken = az account get-access-token --resource https://database.windows.net/ --query accessToken --output tsv
                
                # Deploy DACPAC to Azure SQL Database
                & sqlpackage /Action:Publish /SourceFile:$dacpacFilePath /TargetServerName:$sqlServerName /TargetDatabaseName:$databaseName /AccessToken:$accessToken /p:AllowIncompatiblePlatform=true