
CREATE TABLE [stage].[WideWorldImporters_Sales_Customers]
    (
    [CustomerID] int,
	[CustomerName] nvarchar(100),
	[BillToCustomerID] int,
	[CustomerCategoryID] int,
	[BuyingGroupID] int,
	[PrimaryContactPersonID] int,
	[AlternateContactPersonID] int,
	[DeliveryMethodID] int,
	[DeliveryCityID] int,
	[PostalCityID] int,
	[CreditLimit] decimal,
	[AccountOpenedDate] date,
	[StandardDiscountPercentage] decimal,
	[IsStatementSent] bit,
	[IsOnCreditHold] bit,
	[PaymentDays] int,
	[PhoneNumber] nvarchar(20),
	[FaxNumber] nvarchar(20),
	[DeliveryRun] nvarchar(5),
	[RunPosition] nvarchar(5),
	[WebsiteURL] nvarchar(256),
	[DeliveryAddressLine1] nvarchar(60),
	[DeliveryAddressLine2] nvarchar(60),
	[DeliveryPostalCode] nvarchar(10),
	[DeliveryLocation] geography(max),
	[PostalAddressLine1] nvarchar(60),
	[PostalAddressLine2] nvarchar(60),
	[PostalPostalCode] nvarchar(10),
	[LastEditedBy] int,
	[ValidFrom] datetime2,
	[ValidTo] datetime2
    );
