environments:
 - name: dev
 - name: test
 - name: prod

connection_string: 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=wwi_data_mart;UID=sa;PWD=Password01234;TrustServerCertificate=yes;'

data_source_path:  ./contracts/sources
data_sources:
 - name: wide_world_importers
   is_enabled: True
   type: sql_server
 
 - name: adventure_works
   is_enabled: False
   type: sql_server


data_mart_path:  ./contracts/marts
data_marts:
 - name: wide_world_importers
   is_enabled: True
   type: database

 - name: wide_world_importers
   is_enabled: True
   type: synapse
 
 - name: adventure_works
   is_enabled: False
   type: databricks


