trigger:
- master

pool:
  vmImage: windows-2019

variables:
  solution: '**/*.sqlproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sqlProjectPath: 'core/data_platform' # Adjust this path
  sqlPackagePath: '$(Build.ArtifactStagingDirectory)/data_platform.dacpac'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build SQL Project'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(sqlProjectPath)/*.sqlproj'

    - task: VSBuild@1
      inputs:
        solution: '$(sqlProjectPath)/*.sqlproj'
        msbuildArgs: '/p:Configuration=Release'
        platform: 'Any CPU'
        configuration: 'Release'

    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'    

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'