
dataset:
    name: Application_Cities
    description: Staging table Cities
    enabled: true
    type: staging
    load_sytle: default
    load_method: default

columns:
  - sort_order: 1            
    name: CityID            
    data_type: int                                                                        
            
  - sort_order: 2            
    name: CityName            
    data_type: nvarchar            
    length: 50                                                            
            
  - sort_order: 3            
    name: StateProvinceID            
    data_type: int                                                                        
            
  - sort_order: 4            
    name: Location            
    data_type: geography            
    length: -1                                    
    is_nullable: true                        
            
  - sort_order: 5            
    name: LatestRecordedPopulation            
    data_type: bigint                                                
    is_nullable: true                        
            
  - sort_order: 6            
    name: LastEditedBy            
    data_type: int                                                                        
            
  - sort_order: 7            
    name: ValidFrom            
    data_type: datetime2                                                                        
            
  - sort_order: 8            
    name: ValidTo            
    data_type: datetime2                                                                        
            