
dataset:
    name: Application_SystemParameters
    description: Staging table SystemParameters
    enabled: true
    type: staging
    load_sytle: default
    load_method: default

columns:
  - sort_order: 1            
    name: SystemParameterID            
    data_type: int                                                                        
            
  - sort_order: 2            
    name: DeliveryAddressLine1            
    data_type: nvarchar            
    length: 60                                                            
            
  - sort_order: 3            
    name: DeliveryAddressLine2            
    data_type: nvarchar            
    length: 60                                    
    is_nullable: true                        
            
  - sort_order: 4            
    name: DeliveryCityID            
    data_type: int                                                                        
            
  - sort_order: 5            
    name: DeliveryPostalCode            
    data_type: nvarchar            
    length: 10                                                            
            
  - sort_order: 6            
    name: DeliveryLocation            
    data_type: geography            
    length: -1                                                            
            
  - sort_order: 7            
    name: PostalAddressLine1            
    data_type: nvarchar            
    length: 60                                                            
            
  - sort_order: 8            
    name: PostalAddressLine2            
    data_type: nvarchar            
    length: 60                                    
    is_nullable: true                        
            
  - sort_order: 9            
    name: PostalCityID            
    data_type: int                                                                        
            
  - sort_order: 10            
    name: PostalPostalCode            
    data_type: nvarchar            
    length: 10                                                            
            
  - sort_order: 11            
    name: ApplicationSettings            
    data_type: nvarchar            
    length: -1                                                            
            
  - sort_order: 12            
    name: LastEditedBy            
    data_type: int                                                                        
            
  - sort_order: 13            
    name: LastEditedWhen            
    data_type: datetime2                                                                        
            