pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    variables:
    - group: DEV
    jobs:
    - job: BuildDataFactoryArtifacts
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(Build.Repository.LocalPath)/infrastructure/azure_data_factory'
          verbose: true
        displayName: 'Install npm package'

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.Repository.LocalPath)/infrastructure/azure_data_factory'
          customCommand: 'run build export $(Build.Repository.LocalPath)/infrastructure/azure_data_factory /subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroup)/providers/Microsoft.DataFactory/factories/$(DataFactoryName) "ArmTemplate"'
        displayName: 'Validate and Generate ARM template'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.Repository.LocalPath)'
          artifact: drop

  - stage: dev
    variables:
    - group: DEV
    dependsOn: build
    jobs:
    - job: DeployDataFactoryArtifacts
      steps:
      - download: current
        artifact: drop
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentName: 'PublishADF'
          deploymentScope: 'Resource Group'
          resourceGroupName: '$(ResourceGroup)'
          azureResourceManagerConnection: 'azelia-dev-connection'
          templateLocation: 'Linked artifact'
          location: '$(Location)'
          csmFile: '$(Pipeline.Workspace)/drop/infrastructure/azure_data_factory/ArmTemplate/ARMTemplateForFactory.json'
          csmParametersFile: '$(Pipeline.Workspace)/drop/infrastructure/azure_data_factory/ArmTemplate/ARMTemplateParametersForFactory.json'
          deploymentMode: Incremental